//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeInspector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unicode.zip")]
        public string UnicodeZipFilename {
            get {
                return ((string)(this["UnicodeZipFilename"]));
            }
            set {
                this["UnicodeZipFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<undefined>")]
        public string UnicodeUndefinedLabel {
            get {
                return ((string)(this["UnicodeUndefinedLabel"]));
            }
            set {
                this["UnicodeUndefinedLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<invalid>")]
        public string UnicodeInvalidLabel {
            get {
                return ((string)(this["UnicodeInvalidLabel"]));
            }
            set {
                this["UnicodeInvalidLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UnicodeData.txt")]
        public string UnicodeData {
            get {
                return ((string)(this["UnicodeData"]));
            }
            set {
                this["UnicodeData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unihan_IRGSources.txt")]
        public string Unihan_IRGSources {
            get {
                return ((string)(this["Unihan_IRGSources"]));
            }
            set {
                this["Unihan_IRGSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unihan_OtherMappings.txt")]
        public string Unihon_OtherMappings {
            get {
                return ((string)(this["Unihon_OtherMappings"]));
            }
            set {
                this["Unihon_OtherMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unihan_Variants.txt")]
        public string Unihan_Variants {
            get {
                return ((string)(this["Unihan_Variants"]));
            }
            set {
                this["Unihan_Variants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other-Han.txt")]
        public string OtherAttribution {
            get {
                return ((string)(this["OtherAttribution"]));
            }
            set {
                this["OtherAttribution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int MaxNameHists {
            get {
                return ((int)(this["MaxNameHists"]));
            }
            set {
                this["MaxNameHists"] = value;
            }
        }
    }
}
