//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeInspector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnicodeInspector.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then, choose a character from here..
        /// </summary>
        public static string CharacterListHint {
            get {
                return ResourceManager.GetString("CharacterListHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Unicode codepoint(s) here..
        /// </summary>
        public static string InputCueCode {
            get {
                return ResourceManager.GetString("InputCueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (parts of) a Unicode character name here..
        /// </summary>
        public static string InputCueName {
            get {
                return ResourceManager.GetString("InputCueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Unicode text here..
        /// </summary>
        public static string InputCueText {
            get {
                return ResourceManager.GetString("InputCueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string InspectModeCode {
            get {
                return ResourceManager.GetString("InspectModeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InspectModeName {
            get {
                return ResourceManager.GetString("InspectModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string InspectModeText {
            get {
                return ResourceManager.GetString("InspectModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Inspector.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniHan Mappings.
        /// </summary>
        public static string UniHanMappings {
            get {
                return ResourceManager.GetString("UniHanMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniHan Sources.
        /// </summary>
        public static string UniHanSources {
            get {
                return ResourceManager.GetString("UniHanSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniHan Variants.
        /// </summary>
        public static string UniHanVariants {
            get {
                return ResourceManager.GetString("UniHanVariants", resourceCulture);
            }
        }
    }
}
